"""New revision

Revision ID: 0a0ce2967aee
Revises: de2dcc32f478
Create Date: 2023-05-28 23:25:06.961097

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a0ce2967aee'
down_revision = 'de2dcc32f478'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
